const data = {
 
    products: [
      {
        _id: '1',
        name: 'Double Cheese Margherita',
        category: 'Veg',
        image: '/images/p1.png',
        price: 120,
        countInStock: 10,
        brand: 'PizzaHut',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Farm House',
        category: 'Veg',
        image: '/images/p2.png',
        price: 100,
        countInStock: 20,
        brand: 'PizzaHut',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Mexican Green Wave',
        category: 'Veg',
        image: '/images/p3.png',
        price: 220,
        countInStock: 18,
        brand: 'PizzaHut',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Veg Extravaganza',
        category: 'Veg',
        image: '/images/p4.png',
        price: 78,
        countInStock: 5,
        brand: 'PizzaHut',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'CHEESE N CORN',
        category: 'Veg',
        image: '/images/p5.png',
        price: 65,
        countInStock: 12,
        brand: 'PizzaHut',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Indi Tandoori Paneer',
        category: 'Veg',
        image: '/images/p6.png',
        price: 139,
        countInStock: 7,
        brand: 'PizzaHut',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '7',
        name: 'PEPPER BARBECUE CHICKEN',
        category: 'Veg',
        image: '/images/p7.png',
        price: 245,
        countInStock: 19,
        brand: 'PizzaHut',
        rating: 4.0,
        numReviews: 15,
        description: 'high quality product',
      },

      {
        _id: '8',
        name: 'Chicken Golden Delight',
        category: 'Veg',
        image: '/images/p8.png',
        price: 245,
        countInStock: 19,
        brand: 'PizzaHut',
        rating: 4.0,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '1',
        name: 'Double Cheese Margherita',
        category: 'Veg',
        image: '/images/p1.png',
        price: 120,
        countInStock: 10,
        brand: 'PizzaHut',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Farm House',
        category: 'Veg',
        image: '/images/p2.png',
        price: 100,
        countInStock: 20,
        brand: 'PizzaHut',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Mexican Green Wave',
        category: 'Veg',
        image: '/images/p3.png',
        price: 220,
        countInStock: 18,
        brand: 'PizzaHut',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Veg Extravaganza',
        category: 'Veg',
        image: '/images/p4.png',
        price: 78,
        countInStock: 5,
        brand: 'PizzaHut',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'CHEESE N CORN',
        category: 'Veg',
        image: '/images/p5.png',
        price: 65,
        countInStock: 12,
        brand: 'PizzaHut',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Indi Tandoori Paneer',
        category: 'Veg',
        image: '/images/p6.png',
        price: 139,
        countInStock: 7,
        brand: 'PizzaHut',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
      {
        _id: '7',
        name: 'PEPPER BARBECUE CHICKEN',
        category: 'Veg',
        image: '/images/p7.png',
        price: 245,
        countInStock: 19,
        brand: 'PizzaHut',
        rating: 4.0,
        numReviews: 15,
        description: 'high quality product',
      },
      
    ],
  };
  export default data;